import AppKit
import CryptoKit
import UniformTypeIdentifiers

struct ClipboardItem: Identifiable {
    enum Content {
        case text(String)
        /// Original bytes are kept so copying back and dragging out don't lose quality.
        case image(NSImage, data: Data, fileExtension: String)
    }

    let id = UUID()
    let content: Content
    /// Identifies equal contents, so copying the same thing again moves it to the top.
    let fingerprint: String
    var date: Date
    let sourceAppIcon: NSImage?
}

/// In-memory clipboard history. Nothing is written to disk, and it's gone when the app quits.
@MainActor
final class ClipboardStore: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []
    /// Briefly set after copying an item back, for the "Скопировано" feedback.
    @Published private(set) var lastCopiedID: UUID?

    private static let limit = 40
    private static let maxImageFileSize = 30 * 1024 * 1024

    /// Password managers mark their clipboard entries with these (nspasteboard.org convention).
    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    private let pasteboard = NSPasteboard.general
    private var changeCount: Int
    private var timer: Timer?
    private var copiedResetTask: Task<Void, Never>?

    /// Images dragged out are written here, because Finder and messengers want a file.
    private static let temporaryDirectory = FileManager.default.temporaryDirectory.appending(path: "DynamicIsland-Clipboard")

    init() {
        Self.removeTemporaryFiles()
        changeCount = pasteboard.changeCount
        // macOS has no clipboard change notification; polling changeCount is the standard way.
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
    }

    func copy(_ item: ClipboardItem) {
        pasteboard.clearContents()
        switch item.content {
        case .text(let string):
            pasteboard.setString(string, forType: .string)
        case .image(let image, let data, let fileExtension):
            pasteboard.writeObjects([image])
            if fileExtension == "png" {
                pasteboard.setData(data, forType: .png)
            }
        }
        // Our own write: don't record it as a new entry, just move the item to the top.
        changeCount = pasteboard.changeCount
        moveToTop(item.id)
        flashCopied(item.id)
    }

    /// Copies text made in the notch (a translation, a picked color) and puts it at the top of
    /// the history, marked with the app's own icon.
    func addCopiedText(_ string: String) {
        pasteboard.clearContents()
        pasteboard.setString(string, forType: .string)
        changeCount = pasteboard.changeCount
        guard AppSettings.clipboardHistoryEnabled else { return }

        let content = ClipboardItem.Content.text(string)
        let fingerprint = Self.fingerprint(of: content)
        if let existing = items.first(where: { $0.fingerprint == fingerprint }) {
            moveToTop(existing.id)
            flashCopied(existing.id)
            return
        }
        let item = ClipboardItem(content: content, fingerprint: fingerprint, date: Date(), sourceAppIcon: NSApp.applicationIconImage)
        items.insert(item, at: 0)
        if items.count > Self.limit {
            items.removeLast(items.count - Self.limit)
        }
        flashCopied(item.id)
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
    }

    func clear() {
        items.removeAll()
    }

    /// Text drags as a string; images as a file (for Finder, messengers) and as image data.
    func dragProvider(for item: ClipboardItem) -> NSItemProvider {
        switch item.content {
        case .text(let string):
            return NSItemProvider(object: string as NSString)
        case .image(let image, let data, let fileExtension):
            let provider = Self.writeTemporaryFile(data, fileExtension: fileExtension, date: item.date)
                .flatMap(NSItemProvider.init(contentsOf:)) ?? NSItemProvider()
            provider.registerObject(image, visibility: .all)
            return provider
        }
    }

    // MARK: - Private

    /// The "Скопировано" highlight on a card.
    private func flashCopied(_ id: UUID) {
        lastCopiedID = id
        copiedResetTask?.cancel()
        copiedResetTask = Task {
            try? await Task.sleep(for: .seconds(1.2))
            guard !Task.isCancelled else { return }
            lastCopiedID = nil
        }
    }

    private func poll() {
        guard pasteboard.changeCount != changeCount else { return }
        changeCount = pasteboard.changeCount
        guard AppSettings.clipboardHistoryEnabled else { return }

        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: Self.ignoredTypes), let content = readContent() else { return }

        let fingerprint = Self.fingerprint(of: content)
        if let existing = items.first(where: { $0.fingerprint == fingerprint }) {
            moveToTop(existing.id)
            return
        }

        let sourceIcon = NSWorkspace.shared.frontmostApplication?.icon
        items.insert(ClipboardItem(content: content, fingerprint: fingerprint, date: Date(), sourceAppIcon: sourceIcon), at: 0)
        if items.count > Self.limit {
            items.removeLast(items.count - Self.limit)
        }
    }

    private func readContent() -> ClipboardItem.Content? {
        // Files copied in Finder: keep images, skip everything else.
        let fileURLs = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL]
        if let url = fileURLs?.first {
            guard
                let type = UTType(filenameExtension: url.pathExtension), type.conforms(to: .image),
                let size = try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize, size <= Self.maxImageFileSize,
                let data = try? Data(contentsOf: url),
                let image = NSImage(data: data)
            else { return nil }
            return .image(image, data: data, fileExtension: url.pathExtension.lowercased())
        }

        // Text wins over image data: apps like Excel or Keynote put a picture of copied text alongside it.
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return .text(string)
        }

        for (type, fileExtension) in [(NSPasteboard.PasteboardType.png, "png"), (.tiff, "tiff")] {
            if let data = pasteboard.data(forType: type), let image = NSImage(data: data) {
                // TIFF is huge and poorly supported when dropped elsewhere; store it as PNG.
                if type == .tiff, let png = NSBitmapImageRep(data: data)?.representation(using: .png, properties: [:]) {
                    return .image(image, data: png, fileExtension: "png")
                }
                return .image(image, data: data, fileExtension: fileExtension)
            }
        }
        return nil
    }

    private func moveToTop(_ id: UUID) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        var item = items.remove(at: index)
        item.date = Date()
        items.insert(item, at: 0)
    }

    private static func fingerprint(of content: ClipboardItem.Content) -> String {
        let data: Data
        switch content {
        case .text(let string): data = Data(("text:" + string).utf8)
        case .image(_, let bytes, _): data = bytes
        }
        return SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    /// Called on launch and on quit so dragged images don't outlive the in-memory history.
    static func removeTemporaryFiles() {
        try? FileManager.default.removeItem(at: temporaryDirectory)
    }

    private static func writeTemporaryFile(_ data: Data, fileExtension: String, date: Date) -> URL? {
        let directory = temporaryDirectory
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH.mm.ss"
        let url = directory.appending(path: "\(L("Изображение", "Image")) \(formatter.string(from: date)).\(fileExtension)")
        if !FileManager.default.fileExists(atPath: url.path) {
            guard (try? data.write(to: url)) != nil else { return nil }
        }
        return url
    }
}
